model_trainer:
  n_estimators: 300
  learning_rate: 0.05
  max_depth: 5
  colsample_bytree: 0.9
  random_state: 42


mlflow:
  experiment_name: "oil_retail_price_optimization"
  tracking_uri: "mlruns"